### ISSUE TITLE
主题问题

### ISSUE THREAD

**Issue by DerekHey** [Mybrc91/mybrc91.github.io#1]
Hello，不知道能不能麻烦问你一个问题：
我也在Hexo使用了这套主题，但是在根据教程进行友链独立页面编辑的时候，在_data文件夹内创建links.yaml后，一直报错：
ERROR Process failed: _data/links.yaml
YAMLException: missed comma between flow collection entries at line 1, column 184:
     ... 033\themelangfe2052\themelangcs0{\fonttbl{\f0\fbidi \froman\fcha ..

**Comment by Mybrc91** [comment]
@DerekHey 你把文件内容发出来，报错信息是说少逗号了。

**Comment by DerekHey** [comment]
@Mybrc91 我找到问题了，是我用文本编辑器创建的.yaml文件有问题，我用你代码中的那个修改一下就可以了，我现在就照着你的代码在抄..
现在虽然不报错了，但是我左边的功能栏没出来友链的分类...
还有就是我的About.md文件，我这边编辑没有问题，但是预览和传上去就没有正常显示，显示的是Markdown源码，不知道什么情况...
https://github.com/DerekHey/DerekHey.github.io

**Comment by DerekHey** [comment]
我又搞定了，加了空格就好了... @Mybrc91

**Comment by DerekHey** [comment]
> 但是那个左边的功能栏没出来友链的分类，还是没搞定
这个又被我摸索着搞定了

还有一个问题，我开启了标签功能，左边也不出来标签分类0.0

**Comment by Mybrc91** [comment]
你把源码传到分支上 @DerekHey

**Comment by DerekHey** [comment]
@Mybrc91 已经上传了，麻烦帮忙看看~

**Comment by Mybrc91** [comment]
没看出有什么问题，tag目录也生成了，你`hexo clean`，`hexo g`再试试吧 @DerekHey

**Comment by DerekHey** [comment]
试了，还是只有category，没有tag...

**Comment by Mybrc91** [comment]
config error
